---
name: runtz-landing CI/CD Dev
on:
  push:
    branches:
      - dev

env:
  REGISTRY: registry.local:5000

jobs:
  build-dev:
    name: Build dev image
    runs-on:
      - runtz-runners
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."registry.local:5000"]
              http = true
              insecure = true
      - name: Build and push image
        run: |
          docker buildx build \
            --push \
            --tag ${REGISTRY}/runtz-landing:dev$GITHUB_SHA \
            --build-arg NEXT_PUBLIC_RUNTZ_API_URL="https://engine-dev.runtz.dev" \
            .

  deploy-dev:
    name: Deploy dev
    runs-on:
      - runtz-runners
    needs: build-dev
    container:
      image: runtzdev/deploy-k8s:v1
      credentials:
        username: ${{ vars.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Deploy on dev environment
        run: |
          helm upgrade --install runtz-landing ./helm/runtz-landing \
            -n dev \
            -f helm/environments/dev/values.yaml \
            --set "image.tag=dev$GITHUB_SHA"
